/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package resto;

/**
 *
 * @author ASUS
 */
public class adm extends javax.swing.JPanel {

    /**
     * Creates new form admin
     */
    public adm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setBackground(java.awt.Color.red);
        setForeground(java.awt.Color.lightGray);
        setLayout(null);

        jLabel1.setText("id");
        add(jLabel1);
        jLabel1.setBounds(6, 43, 10, 16);

        jLabel2.setText("nama");
        add(jLabel2);
        jLabel2.setBounds(6, 71, 30, 16);

        jLabel3.setText("no_telp");
        add(jLabel3);
        jLabel3.setBounds(6, 99, 39, 16);

        jLabel4.setText("alamat");
        add(jLabel4);
        jLabel4.setBounds(6, 127, 36, 16);

        jLabel5.setText("username");
        add(jLabel5);
        jLabel5.setBounds(6, 152, 52, 16);

        jLabel6.setText("password");
        add(jLabel6);
        jLabel6.setBounds(6, 180, 60, 16);
        add(jTextField1);
        jTextField1.setBounds(101, 40, 170, 22);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(101, 68, 170, 22);
        add(jTextField3);
        jTextField3.setBounds(101, 96, 170, 22);
        add(jTextField4);
        jTextField4.setBounds(101, 124, 170, 22);
        add(jTextField5);
        jTextField5.setBounds(101, 152, 170, 22);
        add(jTextField6);
        jTextField6.setBounds(101, 180, 170, 22);

        jButton1.setText("buat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(6, 220, 72, 23);

        jButton2.setText("ubah");
        add(jButton2);
        jButton2.setBounds(84, 220, 72, 23);

        jButton3.setText("hapus");
        add(jButton3);
        jButton3.setBounds(6, 249, 72, 23);

        jLabel7.setText("database");
        add(jLabel7);
        jLabel7.setBounds(6, 290, 60, 16);

        jButton4.setText("makanan");
        add(jButton4);
        jButton4.setBounds(6, 312, 79, 23);

        jButton5.setText("kasir");
        add(jButton5);
        jButton5.setBounds(6, 341, 72, 23);

        jButton6.setText("meja");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(6, 370, 72, 23);

        jButton7.setText("minuman");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(102, 312, 82, 23);

        jButton8.setText("user");
        add(jButton8);
        jButton8.setBounds(102, 341, 72, 23);

        jButton9.setText("pembayaran");
        add(jButton9);
        jButton9.setBounds(102, 370, 96, 23);

        jButton10.setText("logout");
        add(jButton10);
        jButton10.setBounds(210, 370, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
