/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package resto;

/**
 *
 * @author ASUS
 */
public class makanan extends javax.swing.JPanel {

    /**
     * Creates new form makanan
     */
    public makanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setBackground(java.awt.Color.red);
        setLayout(null);

        jLabel1.setText("id makanan");
        add(jLabel1);
        jLabel1.setBounds(6, 44, 62, 16);

        jLabel2.setText("nama makanan");
        add(jLabel2);
        jLabel2.setBounds(6, 72, 82, 16);

        jLabel3.setText("harga");
        add(jLabel3);
        jLabel3.setBounds(6, 100, 30, 16);

        jLabel4.setText("stok");
        add(jLabel4);
        jLabel4.setBounds(6, 128, 40, 16);
        add(jTextField1);
        jTextField1.setBounds(125, 41, 170, 22);
        add(jTextField2);
        jTextField2.setBounds(125, 69, 170, 22);
        add(jTextField3);
        jTextField3.setBounds(125, 97, 170, 22);
        add(jTextField4);
        jTextField4.setBounds(125, 125, 170, 22);

        jButton1.setText("buat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(0, 159, 72, 23);

        jButton2.setText("ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(125, 159, 72, 23);

        jButton3.setText("hapus");
        add(jButton3);
        jButton3.setBounds(0, 188, 72, 23);

        jLabel5.setText("database");
        add(jLabel5);
        jLabel5.setBounds(6, 229, 60, 16);

        jButton4.setText("minuman");
        add(jButton4);
        jButton4.setBounds(0, 251, 82, 23);

        jButton5.setText("kasir");
        add(jButton5);
        jButton5.setBounds(125, 251, 72, 23);

        jButton6.setText("pembayaran");
        add(jButton6);
        jButton6.setBounds(0, 280, 96, 23);

        jButton7.setText("user");
        add(jButton7);
        jButton7.setBounds(125, 280, 72, 23);

        jButton8.setText("meja");
        add(jButton8);
        jButton8.setBounds(0, 309, 72, 23);

        jButton9.setText("admin");
        add(jButton9);
        jButton9.setBounds(124, 309, 72, 23);

        jButton11.setText("logout");
        add(jButton11);
        jButton11.setBounds(0, 338, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
