/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasiresto;
/**
 *
 * @author ASUS
 */
public class minuman extends javax.swing.JPanel {

    /**
     * Creates new form minuman
     */
    public minuman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setBackground(java.awt.Color.red);
        setLayout(null);

        jLabel1.setText("id minuman");
        add(jLabel1);
        jLabel1.setBounds(6, 31, 65, 16);

        jLabel2.setText("nama minuman");
        add(jLabel2);
        jLabel2.setBounds(6, 59, 85, 16);

        jLabel3.setText("harga");
        add(jLabel3);
        jLabel3.setBounds(6, 87, 30, 16);

        jLabel4.setText("stok");
        add(jLabel4);
        jLabel4.setBounds(6, 115, 40, 16);
        add(jTextField1);
        jTextField1.setBounds(143, 28, 170, 22);
        add(jTextField2);
        jTextField2.setBounds(143, 56, 170, 22);
        add(jTextField3);
        jTextField3.setBounds(143, 84, 170, 22);
        add(jTextField4);
        jTextField4.setBounds(143, 112, 170, 22);

        jButton1.setText("buat");
        add(jButton1);
        jButton1.setBounds(0, 152, 72, 23);

        jButton2.setText("hapus");
        add(jButton2);
        jButton2.setBounds(0, 181, 72, 23);

        jButton3.setText("ubah");
        add(jButton3);
        jButton3.setBounds(143, 152, 72, 23);

        jLabel5.setText("database");
        add(jLabel5);
        jLabel5.setBounds(6, 222, 50, 16);

        jButton4.setText("makanan");
        add(jButton4);
        jButton4.setBounds(0, 244, 79, 23);

        jButton5.setText("pembayaran");
        add(jButton5);
        jButton5.setBounds(0, 273, 96, 23);

        jButton6.setText("meja");
        add(jButton6);
        jButton6.setBounds(0, 302, 72, 23);

        jButton7.setText("kasir");
        add(jButton7);
        jButton7.setBounds(143, 244, 72, 23);

        jButton8.setText("user");
        add(jButton8);
        jButton8.setBounds(143, 273, 72, 23);

        jButton9.setText("admin");
        add(jButton9);
        jButton9.setBounds(143, 302, 72, 23);

        jButton10.setText("logout");
        add(jButton10);
        jButton10.setBounds(0, 337, 72, 23);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
